CREATE TABLE IF NOT EXISTS users(
  id CHAR(36) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE (email)
);
